### ISSUE TITLE
error upon saving

### ISSUE THREAD

**Issue by cadama** [ostamand/tensorflow-tabnet#12]
Has anyone successfully saved this model?

I am getting
```
TypeError: attentive_transformer_layer_call_fn(x, prior_scales, training, alpha) missing 1 required argument: prior_scales
```
when calling 
```
model.save
```
In the examples I don't see the model being saved so I was wondering if this was ever tested.

Running on tensorflow 2.5

**Comment by nico-unity** [comment]
Multiple argument in `call` method must be put in a list. Ex:

```
def __call__(self, inputs, training):
    x, prior_scales = inputs 
    ...
```

If I have time, ill make the fix later or you can have a shot at it :)

**Comment by cadama** [comment]
Well spotted. Indeed putting this into a list solves the problem!

**Comment by nico-unity** [comment]
If you can make a PR would be nice ! Cheers
