### ISSUE TITLE
Doesn't the model have a TabNet regressor or maybe a multi-class classifier?

### ISSUE THREAD

**Issue by VANRao-Stack** [ostamand/tensorflow-tabnet#6]

**Comment by ostamand** [comment]
Thanks for the answer. Sorry for the delay. 

You can easily add a TabNet regressor by only modifying one line in the current implementation (the head on top of the TabNet embedding). I might add an implementation later or feel free to submit a PR.

https://github.com/ostamand/tensorflow-tabnet/blob/c4caa8f48f86d55b54b6816818047f12e9dc6bf6/tabnet/models/classify.py#L63

As for multi-class classifier it should already be supported thru the `n_classes` argument.

https://github.com/ostamand/tensorflow-tabnet/blob/c4caa8f48f86d55b54b6816818047f12e9dc6bf6/tabnet/models/classify.py#L15
